# Generated by Django 6.0.1 on 2026-02-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='observacoes',
        ),
    ]
